### ISSUE TITLE
关于启动

### ISSUE THREAD

**Issue by limu520** [wuhan005/Asteroid#1]
师傅我是debian10的系统，我到腾了一下午，还是没有办法启动这个前端，师傅可以给一个依赖清单和启动教程嘛，如果打扰到了师傅，对不起，对不起。

**Comment by wuhan005** [comment]
Debian 系统上的 Unity 还未经过测试，因此不大清楚。

由于最近比较忙，没太多时间去写项目的使用文档，之后会补上的。(*^▽^*)
