### ISSUE TITLE
好像用git管理项目的时候出了一点小问题

### ISSUE THREAD

**Issue by Firangizh** [wuhan005/Asteroid#2]
起初我用较高的版本打开的，升级了项目，打开之后没有自动载入main.unity，我怀疑可能是版本高了导致的，于是我下载了，您教程所说的版本，打开之后依然是没有载入main.unity文件，待我手动载入sense\main.unity文件后，并打开main camera ，准备按照教程找到url时，发现挂载的脚本丢失了，我还检查了time，它的脚本也丢失了，应该是全部都丢失了吧，这应该是不正常的，不知道是不是我的操作失误，麻烦您能排查一下，谢谢。

https://s1.ax1x.com/2020/06/08/th54I0.png   2019.1.0f2版本直接打开

https://s1.ax1x.com/2020/06/08/th5oGT.png   2019.1.0f2版本打开手动载入main.unity

**Comment by wuhan005** [comment]
感谢您的反馈。
这个问题我前几天也在排查，是我这边的问题。我不是很清楚 Unity 的话哪些文件是可以 gitignore 的，之前用 GitHub 官方 gitignore 配置 ignore 所有的 meta 文件，导致直接丢失了所有贴图和模型。
所以目前自己在一步步尝试（将代码 push 上来，在 clone 下来看资源是否完整），因此调试的过程挺耗时间的。

**Comment by Firangizh** [comment]
好的，祝愿你能早日调试完成，辛苦了

**Comment by wuhan005** [comment]
现在应该可以了，clone 下来 Script 有的。

（历史遗留问题，很早以前在 Script 文件夹下 gitignore 了 .meta，所以代码都炸了。😅）
