### ISSUE TITLE
关于大屏的一个小疑问

### ISSUE THREAD

**Issue by Dar1in9s** [wuhan005/Asteroid#3]
想问一下就是大屏的标题能不能更改呢？总不能都是D^3CTF 吧

如果能改，我应该怎么改呢？
![image](https://user-images.githubusercontent.com/46131597/87220585-a7bed180-c397-11ea-88bb-06cfd0a9ce67.png)

**Comment by wuhan005** [comment]
双击一下就能编辑了……



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dar1in9 <notifications@github.com&gt;
发送时间: 2020年7月11日 16:58
收件人: wuhan005/Asteroid <Asteroid@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[wuhan005/Asteroid] 大屏的一个小问题 (#3)





 
想问一下就是大屏的标题能不能更改呢？总不能都是D^3CTF 吧
 
如果能改，我应该怎么改呢？

**Comment by wuhan005** [comment]
[v1.0](https://github.com/wuhan005/Asteroid/releases/tag/v1.0) 版本已支持从平台后端获取比赛名。
部署方法请[参照文档](https://cardinal.ink/asteroid/install.html)。
